import type { LangfitDraft, LangSkill, LangTask, Lang, Level, RequiredBy } from "./types";
import { LANG_SKILLS, REQUIRED_BY, levelRank, maxLevel } from "./types";
import { getRule, taskWarnings } from "./rules";

/**
 * The three LangFit outputs, generated by template from VALIDATED rows only.
 * No model writes these: the rationale note is the document an employer may
 * have to stand behind, so it must say exactly what the employer approved and
 * nothing a model made up. The posting text is always produced in both Finnish
 * and English; the note and plan follow the UI locale.
 */

type L = "fi" | "en";

const D = {
  fi: {
    lang: { fi: "Suomi", sv: "Ruotsi", en: "Englanti" } as Record<Lang, string>,
    langLower: { fi: "suomen", sv: "ruotsin", en: "englannin" } as Record<Lang, string>,
    skill: {
      listening: "kuullun ymmärtäminen",
      reading: "luetun ymmärtäminen",
      speaking: "puhuminen",
      writing: "kirjoittaminen",
    } as Record<LangSkill, string>,
    by: { day1: "aloituksesta", m6: "6 kuukauden kuluessa", m12: "12 kuukauden kuluessa" } as Record<RequiredBy, string>,
    rationale: {
      customer_work: "Asiakastyö",
      patient_safety: "Potilasturvallisuus",
      official_responsibility: "Viranomaisvastuu",
      legislation: "Lainsäädäntö",
      none: "Ei työhön perustuvaa syytä",
    } as Record<LangTask["rationaleType"], string>,
    origin: {
      ai: "Tekoälyn ehdotus, työnantaja validoinut",
      example: "Esimerkkirivi, työnantaja validoinut",
      human: "Työnantajan lisäämä",
      rule: "Lakisääteinen vaatimus (lukittu)",
    } as Record<LangTask["origin"], string>,
    yes: "kyllä",
    no: "ei",
  },
  en: {
    lang: { fi: "Finnish", sv: "Swedish", en: "English" } as Record<Lang, string>,
    langLower: { fi: "Finnish", sv: "Swedish", en: "English" } as Record<Lang, string>,
    skill: {
      listening: "listening",
      reading: "reading",
      speaking: "speaking",
      writing: "writing",
    } as Record<LangSkill, string>,
    by: { day1: "from day one", m6: "within 6 months", m12: "within 12 months" } as Record<RequiredBy, string>,
    rationale: {
      customer_work: "Customer work",
      patient_safety: "Patient safety",
      official_responsibility: "Official responsibility",
      legislation: "Legislation",
      none: "No job-based reason",
    } as Record<LangTask["rationaleType"], string>,
    origin: {
      ai: "AI suggestion, validated by the employer",
      example: "Example row, validated by the employer",
      human: "Added by the employer",
      rule: "Statutory requirement (locked)",
    } as Record<LangTask["origin"], string>,
    yes: "yes",
    no: "no",
  },
};

/** ESCO v1.2.1 language-skill labels, the taxonomy side of each level. */
const ESCO_NAME: Record<Lang, string> = { fi: "Finnish", sv: "Swedish", en: "English" };
export function escoLabel(skill: LangSkill, lang: Lang): string {
  const n = ESCO_NAME[lang];
  switch (skill) {
    case "listening":
      return `understand spoken ${n}`;
    case "reading":
      return `understand written ${n}`;
    case "speaking":
      return `interact verbally in ${n}`;
    case "writing":
      return `write ${n}`;
  }
}

const validated = (d: LangfitDraft) => d.tasks.filter((t) => t.validated);
/** Rows where a national language is a hard requirement. */
const isRequired = (t: LangTask) => t.language !== "en" && !t.englishSufficient;

function levelsText(levels: Record<LangSkill, Level>, l: L): string {
  return LANG_SKILLS.filter((s) => levels[s])
    .map((s) => `${D[l].skill[s]} ${levels[s]}`)
    .join(", ");
}

/**
 * Per national language, the cumulative requirement at each milestone: a later
 * milestone only lists skills that rise above what was already required.
 */
function milestones(tasks: LangTask[], lang: Lang) {
  const out: { by: RequiredBy; levels: Record<LangSkill, Level>; top: Level; tasks: LangTask[] }[] = [];
  const sofar: Record<LangSkill, Level> = { listening: null, reading: null, speaking: null, writing: null };
  for (const by of REQUIRED_BY) {
    const group = tasks.filter((t) => isRequired(t) && t.language === lang && t.requiredBy === by);
    if (group.length === 0) continue;
    const rise: Record<LangSkill, Level> = { listening: null, reading: null, speaking: null, writing: null };
    for (const s of LANG_SKILLS) {
      const m = maxLevel(group.map((t) => t.levels[s]));
      if (levelRank(m) > levelRank(sofar[s])) {
        rise[s] = m;
        sofar[s] = m;
      }
    }
    const top = maxLevel(Object.values(rise));
    if (top) out.push({ by, levels: rise, top, tasks: group });
  }
  return out;
}

export function postingText(draft: LangfitDraft, l: L): string {
  const d = D[l];
  const tasks = validated(draft);
  if (tasks.length === 0) return "";
  const lines: string[] = [];
  const nationals = (["fi", "sv"] as Lang[]).filter((lang) => tasks.some((t) => isRequired(t) && t.language === lang));
  const learnsOnJob = tasks.some((t) => isRequired(t) && t.requiredBy !== "day1");

  // Headline, e.g. "Suomi A2 aloituksesta, B1 12 kuukauden kuluessa – tuemme kielen oppimista."
  const heads = nationals.map((lang) => {
    // Only milestones that raise the overall level make the headline.
    let prev: Level = null;
    const ms = milestones(tasks, lang).filter((m) => {
      const rises = levelRank(m.top) > levelRank(prev);
      if (rises) prev = m.top;
      return rises;
    });
    return `${d.lang[lang]} ${ms.map((m) => `${m.top} ${d.by[m.by]}`).join(", ")}`;
  });
  if (heads.length) {
    lines.push(
      heads.join("; ") +
        (learnsOnJob ? (l === "fi" ? " – tuemme kielen oppimista." : " – we support your language learning.") : ".")
    );
  }

  lines.push("");
  lines.push(l === "fi" ? "Kielitaito tehtävittäin:" : "Language skills by task:");
  for (const lang of nationals) {
    for (const m of milestones(tasks, lang)) {
      lines.push(
        `• ${d.lang[lang]}, ${d.by[m.by]}: ${levelsText(m.levels, l)} (${m.tasks.map((t) => t.description.toLowerCase()).join("; ")})`
      );
    }
  }
  const english = tasks.filter((t) => t.language === "en");
  if (english.length) {
    const lv = LANG_SKILLS.reduce(
      (acc, s) => ({ ...acc, [s]: maxLevel(english.map((t) => t.levels[s])) }),
      {} as Record<LangSkill, Level>
    );
    lines.push(`• ${d.lang.en}: ${levelsText(lv, l)} (${english.map((t) => t.description.toLowerCase()).join("; ")})`);
  }
  const advantage = tasks.filter((t) => t.language !== "en" && t.englishSufficient);
  if (advantage.length) {
    const names = advantage.map((t) => t.description.toLowerCase()).join("; ");
    lines.push(
      l === "fi"
        ? `• Englanti riittää tehtäviin: ${names}. Suomen kielen taito on eduksi.`
        : `• English is sufficient for: ${names}. Finnish is an advantage.`
    );
  }
  if (learnsOnJob) {
    lines.push("");
    lines.push(
      l === "fi"
        ? "Tuemme kielen oppimista työn ohessa: työpari, tehtäväkohtainen sanasto ja työpaikkasuomen koulutus."
        : "We support learning Finnish on the job: a work buddy, task-specific vocabulary and workplace Finnish training."
    );
  }
  lines.push(
    l === "fi"
      ? "Kielitaitovaatimukset perustuvat työtehtäviin."
      : "Language requirements are based on the tasks of the job."
  );
  return lines.join("\n");
}

function originText(t: LangTask, l: L): string {
  return D[l].origin[t.origin];
}

export function rationaleNote(draft: LangfitDraft, l: L, date: Date): string {
  const d = D[l];
  const tasks = validated(draft);
  if (tasks.length === 0) return "";
  const rule = getRule(draft.regulated);
  const dateStr = date.toLocaleDateString(l === "fi" ? "fi-FI" : "en-GB");
  const L_ = (fi: string, en: string) => (l === "fi" ? fi : en);
  const out: string[] = [];

  out.push(L_("PERUSTELUMUISTIO – KIELITAITOVAATIMUS", "RATIONALE NOTE – LANGUAGE REQUIREMENT"));
  out.push(`${L_("Tehtävä", "Position")}: ${draft.title || "–"}`);
  out.push(`${L_("Laadittu", "Prepared")}: ${dateStr}`);
  out.push(
    `${L_("Säännelty ammatti", "Regulated profession")}: ${rule ? `${rule.label[l]} – ${rule.statute[l]}` : L_("ei", "no")}`
  );
  out.push("");

  const required = tasks.filter(isRequired).length;
  const englishOk = tasks.filter((t) => t.language !== "en" && t.englishSufficient).length;
  out.push(L_("1. Yhteenveto", "1. Summary"));
  out.push(
    L_(
      `Työ on jaettu ${tasks.length} tehtävään. Kansalliskielen taito on vaatimus ${required} tehtävässä; ${englishOk} tehtävässä englanti riittää.`,
      `The job is split into ${tasks.length} tasks. A national language is required in ${required}; English is sufficient in ${englishOk}.`
    )
  );
  out.push("");

  out.push(L_("2. Tehtäväkohtaiset perustelut", "2. Justification by task"));
  tasks.forEach((t, i) => {
    out.push(`${i + 1}. ${t.description}`);
    out.push(`   ${L_("Kieli", "Language")}: ${d.lang[t.language]} · ${levelsText(t.levels, l) || "–"} · ${d.by[t.requiredBy]}`);
    out.push(`   ${L_("Peruste", "Ground")}: ${d.rationale[t.rationaleType]}${t.rationale.trim() ? ` – ${t.rationale.trim()}` : ""}`);
    if (t.language !== "en") {
      out.push(`   ${L_("Englanti riittää", "English sufficient")}: ${t.englishSufficient ? d.yes : d.no}`);
    }
    out.push(`   ${L_("Alkuperä", "Origin")}: ${originText(t, l)}`);
    const esco = LANG_SKILLS.filter((s) => t.levels[s]).map((s) => escoLabel(s, t.language));
    if (esco.length) out.push(`   ESCO: ${esco.join(", ")}`);
  });
  out.push("");

  const flagged = tasks.filter((t) => taskWarnings(t).some((w) => w === "noRationale" || w === "highWithoutRationale"));
  if (flagged.length) {
    out.push(L_("3. Huomiot", "3. Flags"));
    for (const t of flagged) {
      out.push(
        L_(
          `• "${t.description}": vaatimukselle ei ole kirjattu työhön perustuvaa syytä. Harkitse vaatimuksen keventämistä, siirtämistä myöhemmäksi tai englannin hyväksymistä.`,
          `• "${t.description}": no job-based reason is recorded for this requirement. Consider lowering it, deferring it, or accepting English.`
        )
      );
    }
    out.push("");
  }

  out.push(L_(`${flagged.length ? 4 : 3}. Oikeudellinen tausta`, `${flagged.length ? 4 : 3}. Legal background`));
  out.push(
    L_(
      "Yhdenvertaisuuslaki (1325/2014) kieltää syrjinnän muun muassa kielen perusteella. Kielitaitovaatimus on hyväksyttävä, kun se perustuu työtehtävien todellisiin ja ratkaiseviin vaatimuksiin ja on oikeasuhtainen. Työnantajalla, jonka palveluksessa on säännöllisesti vähintään 30 henkilöä, on oltava yhdenvertaisuussuunnitelma.",
      "The Non-Discrimination Act (1325/2014) prohibits discrimination on grounds including language. A language requirement is acceptable when it rests on genuine and determining requirements of the work and is proportionate. Employers who regularly employ at least 30 people must have an equality plan."
    )
  );
  out.push("");
  out.push(
    L_(
      "Tämä muistio dokumentoi työnantajan perustelut. Se ei ole oikeudellinen lausunto. Tekoälyn ehdotukset on merkitty; jokaisen rivin on hyväksynyt työnantaja. LangFit kuvaa työtä – se ei arvioi hakijoita.",
      "This note documents the employer's reasoning. It is not legal advice. AI suggestions are labelled; every row was approved by the employer. LangFit describes the job – it does not assess applicants."
    )
  );
  return out.join("\n");
}

export function languagePlan(draft: LangfitDraft, l: L): string {
  const d = D[l];
  const tasks = validated(draft);
  if (tasks.length === 0) return "";
  const L_ = (fi: string, en: string) => (l === "fi" ? fi : en);
  const out: string[] = [];
  out.push(L_(`KIELISUUNNITELMA – ${draft.title || "–"}`, `LANGUAGE PLAN – ${draft.title || "–"}`));
  out.push("");

  const sections: [RequiredBy, string][] = [
    ["day1", L_("Aloitus (päivä 1)", "Start (day 1)")],
    ["m6", L_("0–6 kuukautta", "0–6 months")],
    ["m12", L_("6–12 kuukautta", "6–12 months")],
  ];
  for (const [by, heading] of sections) {
    const group = tasks.filter((t) => isRequired(t) && t.requiredBy === by);
    const english = by === "day1" ? tasks.filter((t) => t.language === "en" || t.englishSufficient) : [];
    if (group.length === 0 && english.length === 0) continue;
    out.push(heading);
    for (const t of group) {
      out.push(`• ${t.description}: ${d.langLower[t.language]} ${levelsText(t.levels, l)}`);
    }
    for (const t of english) {
      out.push(`• ${t.description}: ${L_("hoidetaan englanniksi", "done in English")}`);
    }
    out.push("");
  }

  const growth = tasks.filter((t) => isRequired(t) && t.requiredBy !== "day1");
  if (growth.length === 0) {
    out.push(
      L_(
        "Ei kehitystavoitteita: vaatimukset ovat voimassa heti tai englanti riittää.",
        "No development targets: requirements apply from day one or English is sufficient."
      )
    );
    return out.join("\n");
  }

  out.push(L_("Tukitoimet", "Support measures"));
  out.push(L_("• Työpari ensimmäisiksi kuukausiksi", "• A work buddy for the first months"));
  out.push(L_("• Työturvallisuusviestintä opetellaan ensin", "• Safety communication is learned first"));
  out.push(
    L_(
      `• Tehtäväkohtainen sanasto: ${growth.map((t) => t.description.toLowerCase()).join("; ")}`,
      `• Task-specific vocabulary: ${growth.map((t) => t.description.toLowerCase()).join("; ")}`
    )
  );
  out.push(L_("• Työpaikkasuomen opetus työaikana", "• Workplace Finnish lessons during working hours"));
  out.push(
    L_(
      "• Edistymisen seuranta 3 kuukauden välein neljän osa-alueen itsearvioinnilla",
      "• Progress check every 3 months with a four-area self-assessment"
    )
  );
  out.push("");

  const target = maxLevel(growth.flatMap((t) => LANG_SKILLS.map((s) => t.levels[s])));
  const longest = growth.some((t) => t.requiredBy === "m12") ? 12 : 6;
  out.push(L_("RekryKoulutus-ehdotus (luonnos)", "RekryKoulutus proposal (draft)"));
  out.push(`${L_("Koulutus", "Training")}: ${L_("Työpaikkasuomi", "Workplace Finnish")} – ${draft.title || "–"}`);
  out.push(`${L_("Tavoitetaso", "Target level")}: ${target ?? "–"} (${longest} ${L_("kk", "months")})`);
  out.push(
    `${L_("Sisältö", "Content")}: ${L_("tehtäväkohtainen sanasto ja työturvallisuusviestintä", "task-specific vocabulary and occupational-safety communication")}`
  );
  out.push(
    `${L_("Rahoitus", "Funding")}: ${L_("julkinen osuus 70 %, työnantaja 30 % (yhteishankintakoulutus)", "public share 70%, employer 30% (joint-purchase training)")}`
  );
  out.push(
    `${L_("Seuraava askel", "Next step")}: ${L_("ota yhteys alueesi työllisyyspalveluihin (tarkista vastuutaho ja ehdot)", "contact your regional employment services (check the responsible body and terms)")}`
  );
  return out.join("\n");
}
